/**
 * Server-side authorisation.
 *
 * Client checks are convenience, not security. The same permission model is
 * compiled into Firestore Security Rules below. Rules read a denormalised
 * `perms` array on each user document — that array is recomputed and written
 * by `syncUserPermissions()` whenever a role or an assignment changes, so a
 * client can never grant itself a permission it does not hold.
 */
import { db, getDriver } from "./backend";
import { APP_ID } from "./config";
import { ALL_PERMISSION_KEYS, effectivePermissions, type Role } from "./permissions";

/** collection → permission keys required for read / write / delete */
export const COLLECTION_RULES: Record<
  string,
  { read: string | null; write: string; del: string; publicCreate?: string; openCreate?: boolean; selfUpdate?: string }
> = {
  settings: { read: null, write: "settings.edit", del: "security.edit" },
  design: { read: null, write: "design.edit", del: "design.publish" },
  roles: { read: null, write: "roles.edit", del: "roles.delete" },
  users: { read: null, write: "users.edit", del: "users.delete", selfUpdate: "profile.edit" },
  usernames: { read: null, write: "users.edit", del: "users.delete" },
  sessions: { read: "security.view", write: "security.edit", del: "security.edit" },
  battles: { read: null, write: "battles.edit", del: "battles.delete" },
  mcs: { read: null, write: "mcs.edit", del: "mcs.delete" },
  news: { read: null, write: "news.edit", del: "news.delete" },
  events: { read: null, write: "events.edit", del: "events.delete" },
  pages: { read: null, write: "pages.edit", del: "pages.delete" },
  categories: { read: null, write: "categories.manage", del: "categories.manage" },
  tags: { read: null, write: "tags.manage", del: "tags.manage" },
  media: { read: null, write: "media.edit", del: "media.delete" },
  comments: { read: null, write: "comments.edit", del: "comments.delete", publicCreate: "comments.create" },
  chat: { read: null, write: "chat.moderate", del: "chat.moderate", publicCreate: "chat.post" },
  reports: { read: "reports.view", write: "reports.resolve", del: "reports.resolve", publicCreate: "reports.create" },
  notifications: { read: null, write: "notifications.send", del: "notifications.manage" },
  analytics: { read: "analytics.view", write: "analytics.view", del: "logs.purge", openCreate: true },
  audit_logs: { read: "logs.audit", write: "logs.audit", del: "logs.purge" },
  login_logs: { read: "logs.logins", write: "logs.logins", del: "logs.purge" },
  security_logs: { read: "logs.security", write: "logs.security", del: "logs.purge" },
  error_logs: { read: "logs.errors", write: "logs.errors", del: "logs.purge" },
  api_keys: { read: "api.keys", write: "api.keys", del: "api.keys" },
};

export function buildRules(roles: Role[]): string {
  const owner = roles.find((r) => r.slug === "owner")?.id || "role_owner";
  const block = (col: string) => {
    const r = COLLECTION_RULES[col] || { read: null, write: "settings.edit", del: "settings.edit" };
    const read = r.read ? `allow read: if isStaff() && hasPerm('${r.read}');` : "allow read: if true;";
    const create = r.openCreate
      ? "allow create: if true;"
      : r.publicCreate
        ? `allow create: if signedIn() && notBanned() && hasPerm('${r.publicCreate}');`
        : `allow create: if isStaff() && hasPerm('${r.write}');`;
    const update = r.selfUpdate
      ? `allow update: if (isStaff() && hasPerm('${r.write}')) ||
        (signedIn() && request.auth.uid == docId && hasPerm('${r.selfUpdate}') &&
         request.resource.data.roles == resource.data.roles &&
         request.resource.data.perms == resource.data.perms &&
         request.resource.data.banned == resource.data.banned);`
      : `allow update: if isStaff() && hasPerm('${r.write}');`;
    return `    match /${col}/{docId} {
      ${read}
      ${create}
      ${update}
      allow delete: if isStaff() && hasPerm('${r.del}');
    }`;
  };

  return `rules_version = '2';
// FLOW & BARS — generated by Admin → System → Security.
// Deploy with:  firebase deploy --only firestore:rules
service cloud.firestore {
  match /databases/{database}/documents {

    function usersRoot() {
      return /databases/$(database)/documents/artifacts/${APP_ID}/public/data/users;
    }
    function me() { return get(usersRoot() / request.auth.uid).data; }
    function signedIn() { return request.auth != null; }
    function isOwner() { return signedIn() && me().roles.hasAny(['${owner}']); }
    function isStaff() { return signedIn() && ('admin.access' in me().perms); }
    function hasPerm(p) { return signedIn() && (isOwner() || me().perms.hasAny([p])); }
    function notBanned() { return signedIn() && me().banned != true; }

    // Public, signed-in community writes (chat + comments) are allowed for
    // any active member; staff moderation rights are declared per collection.
    match /artifacts/${APP_ID}/public/data {
${Object.keys(COLLECTION_RULES).map(block).join("\n\n")}
    }

    match /{document=**} { allow read, write: if false; }
  }
}
`;
}

/** Denormalise effective permissions onto every user document. */
export async function syncUserPermissions(): Promise<number> {
  const driver = await getDriver();
  const roles = (await driver.list("roles")) as unknown as Role[];
  const users = await driver.list("users");
  let n = 0;
  for (const u of users) {
    const perms = Array.from(effectivePermissions(u.roles || [], roles));
    const current: string[] = u.perms || [];
    const same = current.length === perms.length && current.every((p) => perms.includes(p));
    if (!same) {
      await driver.update("users", u.id, { perms, permsSyncedAt: Date.now() });
      n++;
    }
  }
  return n;
}

export interface Posture {
  label: string;
  ok: boolean;
  detail: string;
}

export async function securityPosture(): Promise<Posture[]> {
  const driver = await getDriver();
  const settings = await driver.get("settings", "security");
  const sec = settings?.value || {};
  const users = await driver.list("users");
  const owners = users.filter((u) => (u.roles || []).includes("role_owner"));
  const admins = users.filter((u) => (u.roles || []).some((r: string) => r !== "role_owner"));
  const banned = users.filter((u) => u.banned);
  const stale = users.filter((u) => !u.perms || Date.now() - (u.permsSyncedAt || 0) > 7 * 864e5);
  return [
    { label: "Identity provider", ok: driver.name === "firestore", detail: driver.name === "firestore" ? "Firebase Auth (server-verified)" : "Local PBKDF2 store — add Firebase env vars for production" },
    { label: "Phone / SMS auth", ok: true, detail: "Removed platform-wide. No phone field exists in any flow." },
    { label: "Brute-force lockout", ok: Boolean(sec.maxAttempts), detail: `${sec.maxAttempts || 5} attempts / ${Math.round((sec.windowMs || 9e5) / 60000)} min window, exponential backoff` },
    { label: "Session lifetime", ok: true, detail: `${sec.sessionLifetimeDays || 30} days, refresh-token based` },
    { label: "Owner accounts", ok: owners.length === 1, detail: owners.length ? owners.map((o) => o.username).join(", ") : "No owner — first registration is promoted" },
    { label: "Staff accounts", ok: true, detail: `${admins.length} non-owner staff` },
    { label: "Banned accounts", ok: true, detail: `${banned.length} suspended` },
    { label: "Permission sync", ok: stale.length === 0, detail: stale.length ? `${stale.length} user docs need resync` : "All user docs carry fresh perms" },
  ];
}

export { ALL_PERMISSION_KEYS, db };
